### ISSUE TITLE
Custom comparison function

### ISSUE THREAD

**Issue by achille-roussel** [etcd-io/bbolt#156]
Hello,

Today the key comparison function used by the database is `bytes.Compare`. In cases where we're dealing with fixed-size integer or ascii keys this makes a lot of sense, but I have a use case for using variable size integers as keys (similar to big.Int), and the order of the keys as defined by `bytes.Compare` is not the natural order of the integer values.

I'd like to explore modifying the package to make the comparison function configurable on a per-bucket basis, but I wanted to get feedback from someone more familiar with the implementation in case there were any major concerns.

**Comment by pixelrazor** [comment]
Gonna spitball some stuff here and maybe try to test it, but it seems like it would be as simple as having the bucket struct have a new member (func(a, b []byte)int) that will default to bytes.Compare, but setable with a new CreateBucket func, then passing that func into the cursor struct when you make a cursor. cursor will then reference its stored comparison func instead of always using bytes.compare. Does anyone think there's something missing with all that?
