### ISSUE TITLE
Add a WAL?

### ISSUE THREAD

**Issue by Lawliet-Chan** [etcd-io/bbolt#193]
Boltdb has no high writing performence because of b-tree  rebalancing.   Shall we add a write-ahead-log ?    Just like innodb.

**Comment by nonpcnpc** [comment]
etcd already has wal so this should be quite easy to implement.

**Comment by CrocdileChan** [comment]
Well, what I say the WAL  is not for etcd, it is just for boltdb. 
Because the writing operation of boltdb is a random writing on disk and this spend more time.  
When we add a wal, it can become sequential writing. It just writes into WAL and then can return OK to client.  After this,  boltdb's freelist can apply this data into data file for reading.
This can be improve more  writing  performance because sequential ops is better random ops  in disk.

**Comment by CrocdileChan** [comment]
When we put the WAL into boltdb, the boltdb will be more complete.

**Comment by CrocdileChan** [comment]
If etcd's wal  is complete enough,  I think you  can separate it and give some docs for using its api.    Glad to see it.

**Comment by nonpcnpc** [comment]
https://github.com/etcd-io/etcd/tree/master/wal

**Comment by ptabor** [comment]
bbolt is just the btree.  If you need WAL, please use `etcd` or another layer build on top.
