### ISSUE TITLE
Suggested documentation clarification on Commit and Rollback

### ISSUE THREAD

**Issue by WBare** [etcd-io/bbolt#221]
As a new user, it was not clear that Rollback and Commit were both closing the transaction especially in light of the example Update pattern where a deferred Rollback is executed after a successful Commit.

In tx.go, I suggest making the following comment changing simply for clarity:

**From:**

>// Commit writes all changes to disk and updates the meta page.
>// Returns an error if a disk write error occurs, or if Commit is
>// called on a read-only transaction.

To:

>// Commit writes all changes to disk, updates the meta page, and
>// closes the transaction. Commit returns an error if a disk write error
>// occurs, or if it is called on a read-only transaction.

**From:**
> // Rollback closes the transaction and ignores all previous updates. Read-only
> // transactions must be rolled back and not committed.

To:

> // Rollback closes the transaction ignoring all updates. Read-only transactions
> // should be closed with Rollback not with Commit. It is sometimes appropriate to
> // defer a Rollback in a block that ultimately has a successful Commit.  A Rollback
> // after a Commit has no effect, but will return a ErrTxClosed error.

**Comment by cenkalti** [comment]
I've sent a PR for updating `Tx.Commit` documentation. Left out `Tx.Rollback` because:
- "must" must remain, we cannot say "should" there because committing read-only transaction causes "tx not writable" error.
- "It is sometimes appropriate to defer a Rollback in a block that ultimately has a successful Commit." Saying "sometimes" felt a bit vague. This pattern can be seen from the examples in README.
- "A Rollback after a Commit has no effect, but will return a ErrTxClosed error." this is expected and no need to say that in my opinion.
