### ISSUE TITLE
bbolt master broke API compatibility

### ISSUE THREAD

**Issue by jrick** [etcd-io/bbolt#449]
[These error variables](https://pkg.go.dev/go.etcd.io/bbolt#pkg-variables) were removed from the package (and moved to internal/common) in 17b18580c7f3f118b730322800d88f2fc44a85ef and this breaks the build for any importer that references these variables if they update to bbolt master branch.  I also see that there's a [v1.4.0 milestone](https://github.com/etcd-io/bbolt/milestone/3) that includes these changes, but this can't be tagged as v1 without breaking semantic versioning.

**Comment by ahrtr** [comment]
Thanks @jrick for raising this issue and sorry for the inconvenience. 

I agree we should try to keep the public API stable & compatible. Due to the infrequency of bbolt release cycle, we might do need to introduce some breaking change in minor release (e.g. 1.4 against 1.3). But I agree that we should still keep the user-facing error variables still visible to users. 

We did some big refactoring in master, and moved some common low level utilities into `internal/common `, which is depended on by the top level package `bbolt`; so we can't simply move the error variable back to the top level package `bbolt`, otherwise it will lead to circle dependency. How about to get all user-facing error variables included in package `bbolt/errors`? It still has some impact on user applications, but at least users can resolve it with minor change. WDYT? cc  @ptabor @jrick @cenkalti @tjungblu 

BTW, we will always keep all public APIs stable & compatible in all 1.3.x releases.

**Comment by jrick** [comment]
Moving all errors to an `errors` package seems fine to me if it fits the refactoring, but it's still a breaking change and a v2 module should be created to represent the break.

**Comment by cenkalti** [comment]
It's not ideal but I am okay with breaking changes in non-major versions.
- It's a breaking change but it's not backwards-incompatible. Users of the library can fix their usage easily by arranging imports.
- People usually use go.mod to pin package versions. Consumers that would break are the ones that will be upgrading to 1.4 explicitly.
- Moving all user facing errors to separate `bbolt/errors` package can make things easier for users.

Another option without breaking consumers is:
- Keep errors where they were in 1.3
- Return internal errors from internal packages
- Wrap internal errors with a translation function which maps internal errors to external errors

**Comment by jrick** [comment]
I opened #452, which simply reexports all errors with the pattern `var ErrFoo = common.ErrFoo`.  This retains API compatibility and there would be no issue with tagging v1.4.0.

**Comment by ahrtr** [comment]
Thanks all for the feedback. I like the second option proposed by @ptabor . Please see also https://github.com/etcd-io/bbolt/pull/452#issuecomment-1498367665 .

**Comment by serathius** [comment]
Recommended followup. Setup an apidiff like in https://github.com/kubernetes/klog/pull/150 to prevent future regressions.

**Comment by ahrtr** [comment]
> Recommended followup. Setup an apidiff like in [kubernetes/klog#150](https://github.com/kubernetes/klog/pull/150) to prevent future regressions.

Sounds good to me. Let me think how to make it as a generic solution, so as to benefit more projects.
