### ISSUE TITLE
Definition of random writes

### ISSUE THREAD

**Issue by mitar** [etcd-io/bbolt#654]
In README it says:

> Sequential write performance is also fast but random writes can be slow

I am not familiar enough with this terminology, but what exactly do "sequential write" and "random write" mean here? Does this mean writing in sequential key order? So writing values for keys in sequential order? So like `1`, `2`, `3` used for keys? And if I would use random strings for keys that would be random writes?

**Comment by Elbehery** [comment]
@mitar 

Bbolt is based on B+Trees data structure. Data is persisted into Disk. The basic unit of storage on Disk is a page.

To perform operations on B+Tree, you need to traverse the tree from Root-Page -> Branch-Pages -> Leaf-Pages. 

if you insert keys in order as you stated above in the example, this is the best case, since the keys will be inserted into one leaf page, regardless if there will split operation or not. On the other hand, if you insert random keys for example `1`, `1000`, 1000000`, these keys will be inserted into separate leaf pages, and they could be far away from each other. This is a bad scenario 

About string keys : Bbolt persist data as `byte[]`, however the data has to stay in order. Inserting, or retrieving or random keys will have worse performance than sequential keys.

**Comment by mitar** [comment]
I see. But use of SSD for storage and potentially large OS file cache should mitigate those random jumps around the tree? I mean, CPU caches would still be less utilized, but it is still a lesser problem than on spinning disks.

Thank you for explaining.
