### ISSUE TITLE
Hash integrity

### ISSUE THREAD

**Issue by downIoads** [etcd-io/bbolt#679]
Greetings,

would it be possible to get some option parameter that allows for reproducible database hashes that are NOT affected by the order of transactions? Currently, you can have two databases that hold the exact same buckets and key-value pairs but their filesystem hashes differ if the order in which the transactions were done is not the same. I am developing a blockchain that uses bbolt and it would be nice to have a database hash that is consistent across different nodes, no matter in which order they processed transactions as long as the final state is the same.

If this is not possible (e.g. for performance reasons), please let me know!

**Comment by ahrtr** [comment]
> their filesystem hashes

Do you mean the hash of the db file? 

>  their filesystem hashes differ if the order in which the transactions were done is not the same

If the answer to above question is YES, then it's expected behaviour to have different hashes. The timing of splitting or merging b+tree nodes might be different if the transactions are done in different order.  

But if you [iterate over all the keys](https://github.com/etcd-io/bbolt?tab=readme-ov-file#iterating-over-keys), and calculate hash yourself, then I believe you will always get the same hash. 

You should also get the same hash after you [compact](https://github.com/etcd-io/bbolt/blob/1906d5a77612fbab4ad25139db55caf92610f95a/cmd/bbolt/main.go#L1622) the db file

**Comment by downIoads** [comment]
thank you, the [compact function](https://github.com/etcd-io/bbolt/blob/main/compact.go#L8) does exactly what i want. have a nice day!
