### ISSUE TITLE
Best Practice for Multiple Puts

### ISSUE THREAD

**Issue by utdrmac** [etcd-io/bbolt#96]
What's the best practice for doing multiple put operations, say, on a slice of a struct? Is it better to range the slice inside db.Update(), or do multiple db.Update() inside the range?

```
func saveInfo(infos []myInfoStruct) error {
  return db.Update(func(tx *bolt.Tx) error {
    for _, o := range infos {
      buf, _ := json.Marshal(o)
      if err := tx.Put(o.key, buf); err != nil {
        return err
      }
    }
    return nil
  })
}
```

or

```
func saveInfo(infos []myInfoStruct) error {
  for _, o := range infos {
    buf, _ := json.Marshal(o)
    err := db.Update(func(tx *bolt.Tx) error {
      if err := tx.Put(o.key, buf); err != nil {
        return err
      }
      return nil
    })

    if err != nil {
      return err  // breaks for-loop on any failure
    }
  }
  return nil
}
```

In re-reading my code above, the 2nd option appears to be less "atomic" if you are considering Put()'ing the entire slice as a single transaction. In the 1st option, if any Put() fails, they will all fail because the Update() would return non-nill. In the 2nd option, several Put-Update's may succeed but the N-th could fail resulting in that element plus all subsequent slice elements to not be added.

**Comment by dtfinch** [comment]
It's better to use a single update with multiple puts.

It syncs to the disk for each update. On most servers it's near instantaneous, due to non-volatile write caching, but on desktops it can slow to around 20 writes per second as you're waiting for the hard disk's rotation. You don't want to multiply that wait for each record in a loop.
